title: Chandra La
theme: jekyll-theme-minimal
description: Welcome to my portfolio! I am a GIS student pursuing my MS at Portland State University. I have a strong environmental background and am interested in conservation, natural resource management, and finding data-driven solutions. I enjoy working on projects that use data sciences to explore, model, or solve environmental issues. 
email: chandral@pdx.edu

