title: Chandra La
theme: jekyll-theme-minimal
logo: IMG_7279_Resized.jpg
description: Welcome to my portfolio! I am a student at Portland State University pursuing my MS in GIS. I have a strong environmental background and am interested in conservation, natural resource management, and finding data-driven solutions. I enjoy working on projects that use data sciences to explore, model, or solve issues. 


